# Generated by Django 2.0.3 on 2018-03-26 19:47

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_standardpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.StructBlock((('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], initial='h1'))), required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(required=False)), ('html', wagtail.core.blocks.RawHTMLBlock(required=False)), ('staff', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('content', wagtail.core.blocks.RichTextBlock(required=True))), required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)))),
        ),
    ]
