# Generated by Django 2.0.3 on 2018-04-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['datetime']},
        ),
    ]
