# Generated by Django 2.0.4 on 2018-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='area',
            field=models.CharField(choices=[('HOME', 'Home'), ('Foreign', 'Foreign')], default='HOME', max_length=200),
        ),
    ]
